services:
  postgres1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres!
    ports:
      - "5432:5432"
  #admin:
  #  image: slydeveloper/spring-boot-admin:1.3
  #  volumes:
  #    - ./comandos/config/admin-application.yml:/opt/spring-boot-admin-docker/application-docker.yml
  #  ports:
  #    - 1111:1111