version: '3.8'

services:

  generic_front:
    build: ./generic_front
    container_name: generic_front
    ports:
      - "8083:8083"
    depends_on:
      - generic
    restart: always
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Dev@2021"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql  # Persistência de dados
      - ./sqlserver/init-scripts:/docker-entrypoint-initdb.d  # Scripts de inicialização
    networks:
      - app-network

  generic:
    build: ./generic
    container_name: generic
    ports:
      - "8092:8092"
    depends_on:
      - sqlserver
    networks:
      - app-network
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Dev@2021

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local

  ### to run -> docker-compose up -d --build
  ### to stop -> docker-compose down
  #admin:
  #  image: slydeveloper/spring-boot-admin:1.3
  #  volumes:
  #    - ./comandos/config/admin-application.yml:/opt/spring-boot-admin-docker/application-docker.yml
  #  ports:
  #    - 1111:1111