
create database pessoa;

SELECT * FROM generic_metadata;

-- TRUNCATE TABLE generic_fields;

-- TRUNCATE TABLE generic_parameters;
-------------------------------------------------------

drop table generic_metadata;
create table public.generic_metadata (
    metadata_id bigint generated by default as identity,
    _sql VARCHAR(4000),
    _limit VARCHAR(10),
    _offset VARCHAR(10),
    primary key (metadata_id)
);


drop table generic_fields;
create table public.generic_fields (
    field_id bigint generated by default as identity,
    _key VARCHAR(255),
    _value VARCHAR(255),
    primary key (field_id),
    metadata_id bigint REFERENCES public.generic_metadata (metadata_id)  ON DELETE CASCADE
);


drop table generic_parameters;
create table public.generic_parameters (
    parameter_id bigint generated by default as identity,
    _key VARCHAR(255),
    _value VARCHAR(255),
    primary key (parameter_id),
    metadata_id bigint REFERENCES public.generic_metadata (metadata_id)  ON DELETE CASCADE
);

-------------------------------------------------
-- LISTA DE TABELAS - ID 1
-------------------------------------------------
SELECT     
    tabs.table_name AS name 
FROM     
    information_schema.tables tabs 
WHERE     
    tabs.table_schema = 'public'     
    AND tabs.table_catalog = 'pessoa' 
ORDER BY    
    tabs.table_name ASC

-------------------------------------------------
-- LISTA DE CONSTRAINTS - ID 2
-------------------------------------------------
SELECT    
    TC.TABLE_NAME       AS pk,     
    CCU.TABLE_NAME      AS fk
FROM    
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC    
    INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU ON         
        CCU.CONSTRAINT_NAME = TC.CONSTRAINT_NAME
WHERE     
    CONSTRAINT_TYPE = 'FOREIGN KEY'    
    AND TC.TABLE_SCHEMA   = 'public'    
    AND TC.TABLE_NAME LIKE :tableName

-------------------------------------------------
-- LISTA DE COLUNAS - ID 3
-------------------------------------------------
SELECT DISTINCT 
     c.table_name       AS table_name,
    c.column_name       AS column_name,        
    c.udt_name          AS udt_name,        
    t.constraint_type   AS constraint_type,        
    t.constraint_name   AS constraint_name,        
    x.to_table          AS to_table 
FROM    
    information_schema.columns c 
    LEFT OUTER JOIN (        
        SELECT  
            t.constraint_type,                
            t.constraint_catalog,                
            t.constraint_schema,                
            t.constraint_name,                
            t.table_catalog,                
            t.table_schema,                
            t.table_name,                
            u.column_name        
        FROM    
            information_schema.constraint_column_usage u        
            LEFT OUTER JOIN information_schema.table_constraints t ON      
                t.table_catalog = u.table_catalog        
                AND t.table_schema = u.table_schema        
                AND t.table_name = u.table_name        
                AND t.constraint_catalog = u.constraint_catalog        
                AND t.constraint_schema = u.constraint_schema        
                AND t.constraint_name = u.constraint_name        
        WHERE   
            t.constraint_type IS DISTINCT 
        FROM 
           'FOREIGN KEY') t ON      
        c.table_catalog = t.table_catalog 
        AND c.table_schema = t.table_schema
        AND c.table_name = t.table_name 
        AND c.column_name = t.column_name
    LEFT OUTER JOIN (  
        SELECT  
            c.conname,          
            t1.relname AS from_table,          
            a1.attname AS from_column,          
            t2.relname AS to_table,          
            a2.attname AS to_column  
        FROM    
            pg_catalog.pg_constraint c,          
            pg_catalog.pg_class t1,          
            pg_catalog.pg_class t2,          
            pg_catalog.pg_attribute a1,          
            pg_catalog.pg_attribute a2,          
            pg_catalog.pg_namespace n1,          
            pg_catalog.pg_namespace n2  
        WHERE   
            c.conrelid = t1.oid  
            AND c.confrelid = t2.oid  
            AND c.contype ='f'  
            AND a1.attrelid = t1.oid  
            AND a1.attnum = ANY(c.conkey)  
            AND a2.attrelid = t2.oid  
            AND a2.attnum = ANY(c.confkey)  
            AND t1.relkind ='r'  
            AND t2.relkind ='r'  
            AND n1.oid = t1.relnamespace  
            AND n2.oid = t2.relnamespace  
            AND n1.nspname NOT IN ('pg_catalog','pg_toast')  
            AND n2.nspname NOT IN ('pg_catalog','pg_toast')  
            AND pg_catalog.pg_table_is_visible(t1.oid)  
            AND pg_catalog.pg_table_is_visible(t2.oid) ) x ON  
        x.from_table = c.table_name
        AND x.from_column = c.column_name 
WHERE   
    c.table_name LIKE '%' 
    AND c.table_schema = 'public'
    AND c.table_catalog = 'pessoa'
ORDER BY 
    table_name, 
    constraint_type,
    to_table