server:
  port: 8092

spring:
  application:
    name: generic
  datasource:
    username: SA
    password: Dev@2021
    url: jdbc:sqlserver://localhost:1433;database=model;encrypt=false;trustServerCertificate=false;loginTimeout=30;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddlAuto: none
    showSql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        jdbc:
          '[time_zone]': UTC

logging:
  level:
    '[org.hibernate]':
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    '[org.springframework.jdbc.core]':
      JdbcTemplate: DEBUG
      StatementCreatorUtils: TRACE